name: Deploy to k8s

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get kubeconfig
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          context: cluster01-aks-cluster-admin
      - uses: Azure/k8s-deploy@v4
        with:
            namespace: 'app'
            manifests: |
              http-echo-deployment.yaml

           